### ISSUE TITLE
not all pics are displayed

### ISSUE THREAD

**Issue by anarchoi** [jveldboom/facebook-gallery#18]
https://www.ni-dieu-ni-maitre.com/fb/index.php

first album says 1200 pics in the album but only the first ones are displayed with the script.

Also, is it possible to display the latest uploaded files first ?

**Comment by jveldboom** [comment]
I think this has to do with a default limit Facebook is putting on the results. For example, if I change the query to have a `LIMIT 500`, it returns 500 results. But without the LIMIT, it only returns 100.

Personally I feel this is a feature rather than a bug. You would not want to display all 1,200+ photos on a page. But 100 of the most recent from an album is a pretty good default.

If you need to increase this, just change [Line 38](https://github.com/jveldboom/facebook-gallery/blob/master/class.facebook-gallery.php#L38) to have a LIMIT. Like this:

```PHP
if($type == 'photos'){$query = "SELECT src,src_big,caption FROM photo WHERE aid = '$id' LIMIT 500";}
```

Also it should display the photos by latest uploaded by default. Are you seeing otherwise?

**Comment by anarchoi** [comment]
https://www.ni-dieu-ni-maitre.com/fb/?id=240032392803318_1073741830&title=Vos+achats+!

latest uploads arent displayed first

**Comment by jveldboom** [comment]
You might want to try adding an ORDER clause at the end of the query to see if it makes a diffence. For example on the same line (#38) mentioned above add `ORDER BY created DESC` right before `LIMIT 500`. So it looks something like this:

```PHP
if($type == 'photos'){$query = "SELECT src,src_big,caption FROM photo WHERE aid = '$id' ORDER BY created DESC LIMIT 500";}
```

If that doesn't work, take a look at https://developers.facebook.com/docs/reference/fql/photo/ which has a ton of other fields you can sort it on. Such as `modified`

**Comment by anarchoi** [comment]
It doesn't work, still same problem - not all images are displayed and they aren't ordered by creation time :( https://www.ni-dieu-ni-maitre.com/fb/?id=240032392803318_1073741830&title=Vos+achats+!

Line 38:
			if($type == 'photos'){$query = "SELECT src,src_big,caption FROM photo WHERE aid = '$id' ORDER BY created DESC LIMIT 500";}
			else{$query = "SELECT aid,object_id,name,size,type FROM album WHERE owner = '$id' ORDER BY created DESC LIMIT 500";}

**Comment by jveldboom** [comment]
I just [tested this on the demo website](http://castletwo.com/facebook-gallery/?id=240032392803318_1073741830&title=Mobile+Uploads#!prettyPhoto) and was able to confirm it does work. Try clearing all the files in the /cache directory and refresh the page.

**Comment by anarchoi** [comment]
Nice, it worked ! Just had to clear the cache. Thanks a lot !

2015-08-19 21:51 GMT-04:00 John Veldboom <notifications@github.com>:

**Comment by jveldboom** [comment]
:+1:

**Comment by anarchoi** [comment]
It suddently stopped working. I even tried re-uploading the default demo
files, but i'm always getting this error:
invalid page id or name

2015-08-19 21:53 GMT-04:00 John Veldboom <notifications@github.com>:

**Comment by jveldboom** [comment]
I believe this is an issue with your cache again since the demo site is still working.

**Comment by anarchoi** [comment]
Still not working again no matter what i do. I tried on 3 different
servers. The cache folder is always chmod 777 how can it be an issue with
my cache when your script is handling the cache write/load.

I just tried again downloading the official release from Github, uploading
it to my server without any modifications (beside chmod 777 on cache
folder) and i still get "invalid page id or name"
https://www.ni-dieu-ni-maitre.com/fb/

Is there an easy way to just disable the cache ?

2015-09-01 22:12 GMT-04:00 John Veldboom <notifications@github.com>:

**Comment by jveldboom** [comment]
Can you post a copy of the index.php file you're using to call the class.facebook-gallery.php ? I think it has to do with the page id being sent.

**Comment by anarchoi** [comment]
I use the default, unmodified index.php file from github.
I think facebook is forcing to use access token now

<html lang="en">
<head>
    <title>Facebook Gallery</title>
    <script src="
https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"
type="text/javascript" charset="utf-8"></script>
    <script src="js/jquery.prettyPhoto.js" type="text/javascript"
charset="utf-8"></script>
    <script src="bootstrap/js/bootstrap-dropdown.js"></script>
    <script src="bootstrap/js/bootstrap-tooltip.js"></script>
    <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="css/styles.css"/>
    <link rel="stylesheet"
href="bootstrap/css/bootstrap-responsive.min.css">
    <link rel="stylesheet" href="css/prettyPhoto.css"/>
    <script type="text/javascript" charset="utf-8">
    $(function () {
        $("a[rel^='prettyPhoto']").prettyPhoto({theme:
'dark_rounded',social_tools: '',deeplinking: false});
        $("[rel=tooltip]").tooltip();
    });
    </script>
</head>
<body>


<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="<?php echo $_SERVER['PHP_SELF'];
?>">Facebook Gallery</a>
            <ul class="nav">
                <li><a href="https://github.com/jveldboom/facebook-gallery
">github</a></li>
                <li><a href="
https://github.com/jveldboom/facebook-gallery/issues">issues</a></li>
                <li class="dropdown"><a href="#" class="dropdown-toggle"
data-toggle="dropdown">example galleries <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="?fid=tacobell">Taco Bell</a></li>
                    <li><a href="?fid=XGames">X Games</a></li>
                    <li><a href="?fid=googlechrome">Google Chrome</a></li>
                </ul>
                </li>
            </ul>
        </div>
    </div>
</div>


<div class="container-fluid">
    <?php
    if(empty($_GET['fid'])){$_GET['fid'] = 'tacobell';} // force if empty
for demo

    require('class.facebook-gallery.php');
    $cache = array('permission' => 'y',
                    'location' => 'cache', // ensure this directory has
permission to read and write
                    'time' => 7200);
    $gallery = new FBGallery($_GET['fid'],'y',$cache);
    ?>
</div>

</body>
</html>

2015-09-22 22:30 GMT-04:00 John Veldboom <notifications@github.com>:

**Comment by jveldboom** [comment]
On [line 50](https://github.com/jveldboom/facebook-gallery/blob/master/index.php#L50) of the index.php file, replace `$_GET['fid']` with "tacobell" to hardcode a page id.

If that works, it's an issue with the $_GET global variable not getting set. You might want to try adding `var_dump($_GET)` and see what get's spit out for the URL https://www.ni-dieu-ni-maitre.com/fb/?fid=XGames

**Comment by anarchoi** [comment]
var_dump returns the following:
 array(1) { ["fid"]=> string(8) "tacobell" }
i hardcoded my page ID but it still doesn't work :
$gallery = new FBGallery("240032392803318",'y',$cache);
cache folder stays empty even after chmod 777

2015-09-22 22:41 GMT-04:00 John Veldboom <notifications@github.com>:

**Comment by jveldboom** [comment]
I'm not really sure what's causing the issue then. Since you already know your page id, you might want to try to comment out the `getPageId()` function call and uncomment the line below - [these two lines](https://github.com/jveldboom/facebook-gallery/blob/master/class.facebook-gallery.php#L18-L19)

Since I'm not able to reproduce this issue, my suggestion is follow the program's path in the class.facebook-gallery.php file and print out the variables to see where the program is failing.

Start with the `getPageId()` function since this is where the "invalid page id or name" is.

**Comment by anarchoi** [comment]
I really can't explain what's going on. I edited class.facebook-gallery to
add an hardcoded variable containing the album ID. The website worked for 5
days so i thought the problem was solved but today it is displaying the
following error:
*"no photos in this gallery"*

So i changed the error message to output the ID:
*else{$gallery = '...no photos in this gallery '.$album_id.'';}*

it returns:


*"...no photos in this gallery 240032392803318_1073741830"*
So the correct album ID is used. I don't understand what's wrong.























*    public function __construct($id,$breadcrumbs,$cache=array())    {
            //$this->id = $this->getPageId($id); // if you're certain
you'll always know the correct page id, just comment this line an uncomment
the line below        $this->id = $id;        $this->breadcrumbs =
$breadcrumbs;        $this->cache = $cache;        $getid =
"240032392803318_1073741830";        $gettitle = "Facebook";
if(empty($getid)){            echo $this->displayAlbums();        }
else{            echo $this->displayPhotos($getid,$gettitle);        }
}*
and here's the file where i call the gallery script:








*    require('class.facebook-gallery.php');    $cache = array('permission'
=> 'y',                    'location' => ''.$baseroot.'/cache', // ensure
this directory has permission to read and write                    'time'
=> 86400);    $gallery = new
FBGallery("240032392803318_1073741830",'y',$cache);*

2015-09-23 8:57 GMT-04:00 John Veldboom <notifications@github.com>:

**Comment by jveldboom** [comment]
Really not sure what to tell you since it works on the demo site http://castletwo.com/facebook-gallery/?id=240032392803318_1073741830&title=Timeline+Photos
