### ISSUE TITLE
invalid page id or name

### ISSUE THREAD

**Issue by joelvilaca** [jveldboom/facebook-gallery#20]
sorry my English but I am Portuguese .

I was testing on localhost but can not for the script to work.

message that appears : invalid page id or name

I have to put some id 's facebook page ? if so where and in what file / line ?
Which defines the id of the page ?

Best regards,
Joel

**Comment by jveldboom** [comment]
Hey Joel,

You need to add your Facebook page id within the array you're injecting into the gallery class. For example on [line 44 from the index.php file](https://github.com/jveldboom/facebook-gallery/blob/master/index.php#L44)

What's your Facebook page? I can take a look to make sure it works with the demo site.
