### ISSUE TITLE
div breadcrumb isnt closed ...

### ISSUE THREAD

**Issue by indiarocks08** [jveldboom/facebook-gallery#22]
Hi , I treid your code and it worked fine , but the div class breadcrumb isnt closed in the facebook class php file .

<div class="container-fluid">

I treid adding </div> to the code but it didnt work .. Pls fix it

**Comment by jveldboom** [comment]
I apologize for the super long delay on this. What DIV is not getting closed? There's no DIV within the breadcrumbs.

**Comment by jveldboom** [comment]
i'm going to close this issue due to no response. feel free to comment again if this needs to be addresses still
