### ISSUE TITLE
Cannot query users by their username

### ISSUE THREAD

**Issue by arelidev** [jveldboom/facebook-gallery#28]
Hey there, I am getting this message:

> Unable to display gallery due to the following error: (#803) Cannot query users by their username

Any thoughts?

**Comment by jveldboom** [comment]
Can you post the Facebook page you're trying to use? Almost sounds like you're trying to display a user's photos which this is not designed to do. It's designed to display _public_ Facebook page galleries.

**Comment by arelidev** [comment]
Ah yes, you're correct, I was trying to display a user's album rather than an FB Page.

**Comment by jveldboom** [comment]
No worries - glad it was something easy and nothing related to FB's recent data changes.
