### ISSUE TITLE
Error: (#15)

### ISSUE THREAD

**Issue by grezom** [jveldboom/facebook-gallery#29]
What is wrong? Some help for me?
`Unable to display gallery due to the following error: (#10) To use 'Page Public Content Access', your use of this endpoint must be reviewed and approved by Facebook. To submit this 'Page Public Content Access' feature for review please read our documentation on reviewable features: https://developers.facebook.com/docs/apps/review.`

**Comment by jveldboom** [comment]
Not sure what the question is. The error message from Facebook seems pretty clear what needs to be done. Am I missing something?

**Comment by grezom** [comment]
Could you closed this thread. I'm waiting for facebook.
